version: '3.8'

services:
  transqa-web:
    build:
      context: ..  # Build from parent directory to access TransQA source
      dockerfile: landing-page-app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static:ro
      - ./templates:/app/templates:ro
      - ../transqa.toml:/app/transqa.toml:ro
      - ../whitelist.txt:/app/whitelist.txt:ro
    environment:
      - PYTHONPATH=/app
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - languagetool
      
  languagetool:
    image: erikvl87/languagetool:latest
    ports:
      - "8081:8010"
    environment:
      - Java_Xms=512m
      - Java_Xmx=1g
