name: Deploy Vue.js Landing Page to GitHub Pages

on:
  push:
    branches: [ main ]
    paths: 
      - 'landing-page-app/vue-frontend/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'landing-page-app/vue-frontend/package.json'
    
    - name: Install dependencies
      working-directory: landing-page-app/vue-frontend
      run: npm install
    
    - name: Build for GitHub Pages
      working-directory: landing-page-app/vue-frontend
      run: npm run build-static
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'landing-page-app/static-dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
